blank_issues_enabled: true
contact_links:
  - name: 💬 Discord (relectures & discussions)
    url: https://discord.gg/A8yUHfsNHF
    about: Pour les discussions de relecture et de traduction, rejoins le serveur.
